# Generated by Django 5.1.1 on 2024-10-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preprocessingFile', models.ImageField(upload_to='images/')),
                ('filterName', models.TextField()),
                ('filteredFile', models.ImageField(upload_to='filtered/')),
            ],
        ),
    ]
